### ISSUE TITLE
v2.1.2 breaks for environments with numpy < 2.1

### ISSUE THREAD

**Issue by kmuehlbauer** [conda-forge/array-api-strict-feedstock#13]
### Solution to issue cannot be found in the documentation.

- [x] I checked the documentation.

### Issue

v2.1.2 has numpy 2.1 as a hard dependency (it raises for lesser versions). But numpy isn't pinned to 2.1 in the feedstock.

### Installed packages

no

### Environment info

no

**Comment by rgommers** [comment]
Yes, that was a dependency min version change in 2.1.2 indeed: https://github.com/data-apis/array-api-strict/blob/main/docs/changelog.md#212-2024-11-07.

Since gh-12 just merged through automerge, no review could take place in time to catch that. @asmeurer do we want to change that setting? This isn't ideal it looks like.

**Comment by asmeurer** [comment]
Ah I didn't realize the feedstock would merge itself. I would have hoped the autoupdate bot would catch that. 

It does need to be pinned. I think we can just update it and bump the build number.

**Comment by rgommers** [comment]
gh-14 does the pinning.

**Comment by asmeurer** [comment]
By the way, in the future the only reason the min version of numpy should need to be bumped is if there is some array api change we cannot easily emulate in pure Python (in this case, the new dlpack features).

**Comment by kmuehlbauer** [comment]
Are those changes also needed for 2.1.1? Version 2.1 worked fine AFAICT.

**Comment by jakirkham** [comment]
> Ah I didn't realize the feedstock would merge itself. I would have hoped the autoupdate bot would catch that.

It will once Grayskull is enabled

xref: https://github.com/conda-forge/array-api-strict-feedstock/issues/9
